In [1]:
#importing necessasary libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston

In [4]:
data=load_boston()

In [9]:
data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [ ]:
#Converting into data frame

In [10]:
df=pd.DataFrame(data.data)

In [11]:
df.sample(5)

0     1      2    3       4      5     6       7     8      9   \
227  0.41238   0.0   6.20  0.0  0.5040  7.163  79.9  3.2157   8.0  307.0   
428  7.36711   0.0  18.10  0.0  0.6790  6.193  78.1  1.9356  24.0  666.0   
14   0.63796   0.0   8.14  0.0  0.5380  6.096  84.5  4.4619   4.0  307.0   
273  0.22188  20.0   6.96  1.0  0.4640  7.691  51.8  4.3665   3.0  223.0   
332  0.03466  35.0   6.06  0.0  0.4379  6.031  23.3  6.6407   1.0  304.0   

       10      11     12  
227  17.4  372.08   6.36  
428  20.2   96.73  21.52  
14   21.0  380.02  10.26  
273  18.6  390.77   6.58  
332  16.9  362.25   7.83

In [12]:
df.columns=data.feature_names

In [13]:
df.sample(5)

CRIM   ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
102   0.22876  0.0   8.56   0.0  0.520  6.405   85.4  2.7147   5.0  384.0   
158   1.34284  0.0  19.58   0.0  0.605  6.066  100.0  1.7573   5.0  403.0   
387  22.59710  0.0  18.10   0.0  0.700  5.000   89.5  1.5184  24.0  666.0   
4     0.06905  0.0   2.18   0.0  0.458  7.147   54.2  6.0622   3.0  222.0   
208   0.13587  0.0  10.59   1.0  0.489  6.064   59.1  4.2392   4.0  277.0   

     PTRATIO       B  LSTAT  
102     20.9   70.80  10.63  
158     14.7  353.89   6.43  
387     20.2  396.90  31.99  
4       18.7  396.90   5.33  
208     18.6  381.32  14.66

In [14]:
y=data.target

In [15]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [17]:
x=df

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [20]:
#standardizing the data set

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
scaler=StandardScaler()

In [25]:
x_train=scaler.fit_transform(x_train)
x_test-=scaler.transform(x_test)

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [29]:
model=LinearRegression()

In [30]:
model.fit(x_train,y_train)

LinearRegression()

In [31]:
mse=cross_val_score(model,x_train,y_train,scoring='neg_mean_squared_error',cv=10)

In [32]:
mse

array([-20.96899446, -28.56556055, -48.78676527, -17.90181938,
       -27.86935858, -24.85480776, -18.65321599, -18.02764879,
       -13.94804652, -35.9303906 ])

In [33]:
np.mean(mse)

-25.550660791660786

In [34]:
y_pred=model.predict(x_test)

In [35]:
y_pred

array([  -78.64177745,    39.19075152,  -711.25183581,   -70.36162982,
        -617.41317946,  -257.32744164,  -129.24054625,  -340.79765768,
        -594.5435507 ,  -228.15698005,   -79.40868657,  -129.71919233,
       -1022.71925183,  -241.07708408,   -81.5956019 ,  -604.19861914,
          29.00968942,  -683.01878042,    68.27588578,  -614.15967932,
          62.54201623,    29.7028755 ,  -186.34123985,   -56.06327539,
        -679.78320828,  -658.00294012,  -214.37868464, -1010.82266431,
         -89.65348518,  -225.15774801,   -96.35933384,   -54.68666939,
        -608.68284072,  -595.7608499 ,  -687.19354411,  -382.33829964,
           8.65675306,    27.64184455,   -84.14919027,   -90.85601183,
        -248.73701333,    63.02105946,   121.92659382,  -148.29839201,
         -46.69976939,  -609.57229336,  -173.14068217,   -81.68731761,
        -601.91806623,   -52.71411679,  -105.1415735 ,    73.1341427 ,
        -135.71745796,  -201.08955487,     9.26130056,  -582.94300957,
      

In [42]:
from sklearn.metrics import r2_score

In [44]:
rsquare=r2_score(y_pred,y_test)

In [49]:
rsquare

-0.85849088152208